# Generated by Django 5.1.6 on 2025-03-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.user_tbl')),
            ],
        ),
    ]
