# Generated by Django 5.1.6 on 2025-04-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0004_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sold_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sold_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sold_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artsapp.user_tbl'),
        ),
    ]
