# Generated by Django 5.1.6 on 2025-04-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0005_post_price_post_sold_date_post_sold_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sold_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sold_to',
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.user_tbl')),
            ],
        ),
    ]
