# Generated by Django 5.1.6 on 2025-04-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0006_remove_post_sold_date_remove_post_sold_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(default='not accepted', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='sold_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sold_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artsapp.user_tbl'),
        ),
    ]
