# Generated by Django 5.1.6 on 2025-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0007_auction_status_post_sold_date_post_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_amount',
            field=models.FloatField(null=True),
        ),
    ]
