# Generated by Django 5.1.6 on 2025-04-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0010_vlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artsapp.artist_tbl'),
        ),
    ]
