# Generated by Django 5.1.6 on 2025-04-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0013_events_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.IntegerField(null=True),
        ),
    ]
