# Generated by Django 5.1.6 on 2025-04-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0014_events_max_participants_events_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.IntegerField(null=True)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.user_tbl')),
            ],
        ),
    ]
