# Generated by Django 5.1.6 on 2025-04-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artsapp', '0015_bookslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artsapp.artist_tbl'),
        ),
    ]
